Correction suggestion in include
I think there is a header import error. I'm a layman in C ++, but I think the import path is incomplete, because in k2_tree_test.cpp is ["#include sdsl/k2_tree.hpp"], but this file is not in the ["sdsl/"] directory, but in ["sdsl/include/"]. Detail of the error obtained in the compilation: 

$ make k2_tree_test
g++     k2_tree_test.cpp   -o k2_tree_test
k2_tree_test.cpp:1:28: fatal error: sdsl/k2_tree.hpp: Arquivo ou diretório não encontrado
 #include "sdsl/k2_tree.hpp"
                            ^
compilation terminated.
make: ** [k2_tree_test] Erro 1